### ISSUE TITLE
Storage Implementation

### ISSUE THREAD

**Issue by dividebyzero** [fahrgemeinschaft/share-square-hub#1]
Hub is a statefull application running in containers. We need to store data and state in a database.
Implementation should make use of Spring Boot JPA Repositories. A mapping between the core datamodels and storage entities would be fine.  implementation should be able to create initial schemas on an empty storage. implementation should be used as a delegate in or implementation of interface _IRepository<T extends IShareSquareObject>_. 
tech requirements:
- sql based storage engine
- unit tests
- h2 database used for unit testing
- default configuration option in spring-style application.properties file
- configuration **must** be overwriteable by environement variables
- env vars **must not** use "." in names but "_" instead for docker/openshift compatibility

**Comment by yncyrydybyl** [comment]
does "h2 database used for unit testing" the in memory database?

**Comment by dividebyzero** [comment]
yes, h2 in memory database for testing.
e.g. https://www.baeldung.com/spring-boot-h2-database

**Comment by kat-ka** [comment]
Do you maybe have an offer test JSON for a POST call to http://localhost:8080/offers/ i can use?

**Comment by kat-ka** [comment]
Tests are green:
https://jenkins.apps.prod.rd2g.de/job/share-square-hub-testing/16/HTML_20Report/

Deployed to the test instance https://share2hub-r2g-api-dev.apps.prod.rd2g.de

Database can be viewed at
https://share2hub-r2g-api-dev.apps.prod.rd2g.de/h2-console
as described in the [README.md](https://github.com/fahrgemeinschaft/share-square-hub/blob/7c1ab6d/README.md)
