### ISSUE TITLE
Testserver does not evaluate the authorization header

### ISSUE THREAD

**Issue by gitterrost4** [fahrgemeinschaft/share-square-hub#6]
In order to test whether Authorization via oauth2 works, the test server needs to evaluate the Authorization-Header and refuse connection with a missing or invalid JWT.

- missing jwt
- wrong format for jwt
- not valid from https://sso-r2g-api-dev.apps.prod.rd2g.de/auth/

**Comment by kat-ka** [comment]
Deployed to Test https://share2hub-r2g-api-dev.apps.prod.rd2g.de

The test instance uses Keycloak realm "master" and scope "order" for authorization.
To generate the access token client id "share2-hub-cantamen" can be used for example.

Some details are in the README.md file.
