### ISSUE TITLE
Testserver contains no targetSystems

### ISSUE THREAD

**Issue by gitterrost4** [fahrgemeinschaft/share-square-hub#9]
The test server at share2hub-r2g-api-dev.apps.prod.rd2g.de does not contain any target systems and hence (I think) makes it impossible to create offers. Can a dummy target system be inserted into that test system, please?

**Comment by kat-ka** [comment]
GET https://share2hub-r2g-api-dev.apps.prod.rd2g.de/targetsystems will return a list of example target systems.
